### ISSUE TITLE
Testing scripts: Java processes don't receive signals

### ISSUE THREAD

**Issue by SolalPirelli** [LPD-EPFL/da15-s4#2]
In the s4_{correctness, performance}.sh files, when sending signals to S4, `$!` returns the ID of the shell that launched S4, not of the S4 process itself. So even `kill -KILL` doesn't kill the Java process.

I suppose the solution is to kill processes using that ID as the parent process ID, but I don't know how to do that. (I know it's simple to do on Windows, but I have near-zero sh knowledge :( )

**Comment by rhpatra** [comment]
The scripts are running fine.
$! returns the pid of the last started background process.
You need to start the s4 as a background process.

**Comment by Gilthoniel** [comment]
Same issue than Solal. First of all, the PID of the child is the id of the s4 job, but when you start a java application without 'exec', it's a new process ID. If you add exec before 'java -cp ...', the script is working fine to kill the children but the SIGINT isn't catched.

**Comment by Gilthoniel** [comment]
@SolalPirelli You can add an 'exec' command in the s4 file before the java command and then replace the SIGINT signal in the sh and the App.java with SIGHUP for instance. The SIGINT signal has a different behaviour, this is why we cannot handle it in jobs

**Comment by SolalPirelli** [comment]
Indeed, HUP works, thanks @Gilthoniel. (on the EPFL's Ubuntu machines at least, not on Windows even with ported *nix utilities)

@rpatra, could you please change the assignment so that we're required to handle SIGHUP instead?

**Comment by rhpatra** [comment]
Sorry. The assignment cannot be changed. Many students have already submitted correct solutions.

**Comment by SolalPirelli** [comment]
Then... how do we handle SIGINT in Java? The code you provided doesn't work.

**Comment by rhpatra** [comment]
The codes work perfectly fine. Students have tested their solutions on Ubuntu 14.04 using the same scripts before submitting. But unfortunately I cannot help you in your implementations. We cannot award bonus points to everyone.

**Comment by SolalPirelli** [comment]
Look, there are 2 people here and 2 people in the comments of commit 728242ddd2fd3f90b5b9276d5b9e45fcdf95bcd1 telling you the code you provided does not work. You replied that we might need to "fix" our S4, even though we're using the one you provided.

Here is what I just did on an x86_64 Ubuntu 14.04 from the EPFL's virtual machines:

``` sh
git clone https://github.com/LPD-EPFL/da15-s4
cd da15-s4
bash s4_correctness.sh
```

The processes do not receive the SIGINT, even after adding `exec` to the ./s4 file.

Either there's some weird configuration issue that only some of the students are running into, or your skeleton doesn't do what you think it does.

**Comment by ciprianf** [comment]
The behavior is very strange indeed. SIGINT seems to be masked in some mysterious ways in some cases. For example, if one replaces the call to './s4' with 'java -cp target/da15-s4-1.0-SNAPSHOT.jar ch.epfl.lpd.App' and then calls './s4_correctness.sh' then the signal is masked, however calling 'source s4_correctness.sh' works fine.

@rpatra I think nobody successfully tested their implementation using s4_{correctness, performance} since the skeleton provided is not working.

**Comment by popovicradmila** [comment]
Yup, I agree with you @ciprianf . Same here.

**Comment by rhpatra** [comment]
For people using java, you can use: The new scripts for java only. You can test with those ones.
For people using other programming languages: Use the previous ones.

Please mention during your submission, in the subject, the programming language you are using.

**Comment by Gilthoniel** [comment]
Thanks

**Comment by adizere** [comment]
The `correctness` and `performance` bash scripts are just for your reference; basic examples to help you with the development and get an idea of how the testing shall look like. Same goes for the sample `input` and `output` files -- and actually for this whole repository.

We may -- or may not -- use slightly different setups, or more devious tricks. As long as your implementation adheres to the requirements you should be fine.

Anyway, if errors slipped in the code in this repository, the fault is mine. Thanks Rhicheek for handling this!
